config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'topos#index'
  resources :topos, only: [:index, :show] do
    resources :comments, only: [:new, :create, :update]
    post :toggle_favorite, on: :member
    get :river_data, on: :member
  end
  resources :favorites, only: [:index, :delete]
  resources :users, only: [:show]
  resources :addresses, only: [:index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  has_many :departures, foreign_key: :departure_id, class_name: "Topo"
  has_many :arrivals, foreign_key: :arrival_id, class_name: "Topo"
  geocoded_by :name
  after_validation :geocode, if: :will_save_change_to_name?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :topo
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topo
  has_one :river, through: :topo
end

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :topo
end

app/models/river.rb
class River < ApplicationRecord
  has_many :topos

  def safe?
    true
  end
end

app/models/topo.rb
class Topo < ApplicationRecord
  belongs_to :river
  belongs_to :departure, class_name: "Address"
  belongs_to :arrival, class_name: "Address"
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :levels, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_by_topo_and_river,
    against: [ :name ],
    associated_against: {
      river: [ :name, :country, :region, :department ]
    },
    using: {
      tsearch: { prefix: true }
  }

  scope :levels, -> (levels) do
    joins(:levels).where(levels: {difficulty: levels})
  end

  def has_severity_2_alert?
    comments.where(category: "alert", severity: 'Impraticable', active: true).any?
  end

  def has_alert?
    comments.where(category: "alert", active: true).any?
  end

  def find_level
    ints = levels.map(&:difficulty)
    int_to_rom(ints)
  end

  private

  def int_to_rom(ints)
    ar = []
    int_to_roman = {  1 => 'I',
                      2 => 'II',
                      3 => 'III',
                      4 => 'IV',
                      5 => 'V',
                      6 => 'VI' }
    ints.each { |int| ar << int_to_roman[int] }
    ar
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites
  has_many :topos, through: :favorites
  has_many :comments
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
    @addresses = Address.all
    @markers = @addresses.geocoded.map do |address|
      {
        lat: address.latitude,
        lng: address.longitude,
        info_window: render_to_string(partial: "info_window", locals: { address: address }),
      }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @topo = Topo.find(params[:topo_id])
    @comment = Comment.new
  end

  def create
    comment = Comment.new(params_comment)
    comment.active = true
    comment.category = 'alert'
    comment.user = current_user
    comment.topo_id = params[:topo_id]
    if comment.save
      redirect_to topo_path(params[:topo_id])
    else
      render :new
    end
  end

  def update
    comment = Comment.find(params[:id])
    comment.active = false
    comment.save
    redirect_to topo_path(params[:topo_id])
  end

  private

  def params_comment
    params.require(:comment).permit(:alert_type, :severity, :description)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = Favorite.where(user_id: current_user.id) # => array d'instance de fav
    @topos_fav = @favorites.map(&:topo) # => array d'instance de topo
    @rivers_fav = @topos_fav.map(&:river) # => array d'instance de river
    @topos_fav_river_name = @rivers_fav.map(&:name)

  end

  def delete
    favorite = Favorite.find(user_id: params[:user_id], topo_id: params[:topo_id])
    favorite.destroy
  end

  private

  def params_topo
    params.permit(:topo_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/topos_controller.rb
class ToposController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      @topos = Topo.search_by_topo_and_river(params[:query])

    else
      find_topo_by_address
      @topos = Topo.all if @topos.count.zero?
    end

    if params[:levels].present?
      @topos = @topos.levels(params[:levels])
    end
  end

  def toggle_favorite
    topo = Topo.find(params[:id])

    @fav = Favorite.find_by(user: current_user, topo: topo)
    if @fav
      @fav.destroy
    else
      @fav = Favorite.create(user: current_user, topo: topo)
    end
    redirect_to topo_path(params[:id])
  end

  def show
    @topo = Topo.find(params[:id])
    @departure = Address.find(@topo.departure_id)
    @arrival = Address.find(@topo.arrival_id)

    @comments = Comment.where(topo: @topo).sort_by(&:updated_at).reverse
    @alerts_count = @comments.select { |comment| comment.category == 'alert' && comment.active == true }.count
    @favorite = Favorite.where(user: current_user, topo: @topo).exists?
  end

  def river_data
    @topo = Topo.find(params[:id])

    stats = StatsForRiver.call(@topo.river)

    data = stats.each do |station|
      station[:data] = station[:data].map { |set| [set[:date], set[:level]] }.to_h
    end
    render json: data.to_json
  end

  private

  def find_topo_by_address
    ip = request.remote_ip
    ip = `curl http://ipecho.net/plain` if ip == "::1"
    address = Geocoder.search(ip)
    topo_addresses = Address.near("#{address[0].city}, #{address[0].country}", 100)
    @topos = []
    topo_addresses.each do |topo_address|
      sql_query = "departure_id = #{topo_address.id} OR arrival_id = #{topo_address.id}"
      topo = Topo.where(sql_query)
      @topos << topo[0]
    end
  end
end

  # def water_data
  #   series_a = {
  #     "2021-08-31 07:05:00" => 30,
  #     "2021-08-31 08:05:00" => 100,
  #     "2021-08-31 09:05:00" => 80,
  #   }
  #   series_b = {
  #     "2021-08-31 07:05:00" => 100,
  #     "2021-08-31 08:05:00" => 10,
  #     "2021-08-31 09:05:00" => 8,
  #   }
  #   data = [
  #     {name: "Station A", data: series_a, color: "orange"},
  #     {name: "Station B", data: series_b, color: "black"}
  #   ]
  #   ap data
  #   return data
  # end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def int_to_roman(int)
    { 1 => 'I',
      2 => 'II',
      3 => 'III',
      4 => 'IV',
      5 => 'V',
      6 => 'VI' }[int]
  end

  def rom_to_int(rom)
    { 'I' => 1,
      'II' => 2,
      'III' => 3,
      'IV' => 4,
      'V' => 5,
      'VI' => 6 }[rom]
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/addresses/_info_window.html.erb
<h2><%= address.name.capitalize %></h2>

app/views/addresses/index.html.erb
<div id="map"
     style="width: 100vw; height: 100vh;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/comments/new.html.erb
<div class='container'>
  <%= simple_form_for [@topo, @comment] do |f| %>
    <%= f.input :alert_type, :collection => ['Arbre', 'Barage', 'Eboulement'], :include_blank => false %>
    <%= f.input :severity, :collection => ['Praticable', 'Impraticable'], :include_blank => false %>
    <%= f.input :description, as: :text %>
    <%= f.button :submit, value:"Ajouter le danger" %>
  <% end %>
</div>

app/views/favorites/index.html.erb
  <div class="container">

    <div class='fav-title'>
      <h2>Favoris (<%= @favorites.count == 0 ? 0 : @favorites.count %>)</h2>
    </div>

    <hr>

    <% if @favorites.any? %>
      <div class='fav-river-title'>
        <% current_user.topos.group_by {|t| t.river.name}.sort.to_h.each do |river_name, topos| %>
          <h2 class='river-name'><%= river_name.capitalize %></h2>
          <%= render "shared/topos-cards", topos: topos.sort_by(&:name) %>
        <% end %>
    <% else %>
      <div id="fav-false">
        <p id="fav-message"> Pas encore de topos préféré 💔 </p>
        <div id="fav-gif">
          <iframe src="https://i.giphy.com/media/3o6MbbcFfp6DGDUiPK/giphy.webp" width="100%" height="100%" style="position:absolute"
                      frameBorder="0" class="giphy-embed" allowFullScreen>
          </iframe>
        </div>
      </div>
    <% end %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <%= favicon_link_tag %>
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Reste du head à garder ? -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="robots" content="index, follow">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="manifest" href="/manifest.json">
    <link rel="apple-touch-icon" href="/icon_512.png">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div>
      <%= yield %>
    </div>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-bottom navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to root_path, class: "nav-link" do %>
    <% if params[:controller] == 'topos' && params[:action] == 'index' %>
      <svg width="31" height="30" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" />
      </svg>
    <% else %>
      <svg width="31" height="30" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
      </svg>
    <% end %>
  <% end %>

  <%= link_to addresses_path, class: "nav-link" do %>
    <% if params[:controller] == 'addresses' && params[:action] == 'index' %>
      <svg width="30" height="30" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M12 1.586l-4 4v12.828l4-4V1.586zM3.707 3.293A1 1 0 002 4v10a1 1 0 00.293.707L6 18.414V5.586L3.707 3.293zM17.707 5.293L14 1.586v12.828l2.293 2.293A1 1 0 0018 16V6a1 1 0 00-.293-.707z" clip-rule="evenodd" />
      </svg>
    <% else %>
      <svg width="30" height="30" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7" />
      </svg>
    <% end %>
  <% end %>

  <%= link_to favorites_path, class: "nav-link" do %>
    <% if params[:controller] == 'favorites' && params[:action] == 'index' %>
      <svg width="35" height="32" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
      </svg>
    <% else %>
      <svg width="35" height="32" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
      </svg>
    <% end %>
  <% end %>

  <%= link_to root_path, class: "nav-link" do %>
    <%# <% if params[:controller] == 'favorites' && params[:action] == 'index' %>
      <%# <svg width="31" height="30" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-6-3a2 2 0 11-4 0 2 2 0 014 0zm-2 4a5 5 0 00-4.546 2.916A5.986 5.986 0 0010 16a5.986 5.986 0 004.546-2.084A5 5 0 0010 11z" clip-rule="evenodd" />
      </svg> %>
    <%# <% else %>
      <svg width="31" height="30" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    <%# <% end %>
  <% end %>

</div>

app/views/shared/_topos-cards.html.erb
  <div class="card-container">
    <% topos.each do |topo| %>
      <%= link_to topo_path(topo), class: 'card-product' do %>
        <%= image_tag topo.image_url %>
        <div class='card-infos'>
          <div class='infos-name'>
            <div class='naming-div'>
              <h4 class='topo-title'><%= "#{topo.river.name.capitalize} #{topo.name.capitalize}" %></h4>
              <div class='topo-level-cont'>
              <h4 class='topo-level'><%= topo.find_level.count > 1 ? "#{topo.find_level[0]} - #{topo.find_level[1]}" : "#{topo.find_level[0]}" %></h4>
              </div>
            </div>
          </div>
          <div class='country-div'>
            <div class="flag">
              <svg xmlns="http://www.w3.org/2000/svg" width="27" height="18"><rect width="27" height="18" fill="#ED2939"/><rect width="18" height="18" fill="#fff"/><rect width="9" height="18" fill="#002395"/></svg>
            </div>
              <p><%= topo.river.department %></p>
          </div>
          <div class="alert-div">
            <div class="alert-icons">
              <% if topo.has_alert? %>
                <div class="alert-level <%= topo.has_severity_2_alert? ? 'severity2' : '' %>"><i class="fas fa-exclamation-triangle"></i></div>
              <% end %>
              <% if topo.river.safe? %>
                <div class='safe'><i class="fas fa-check"></i></div>
              <% else %>
                <div class='unsafe'><i class="fas fa-times"></i></div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/topos/index.html.erb
  <%# INFO-POP-UP -->  TO RENDER %>

  <div class="info-bg">
    <div class='info-legend'>
      <h4>Niveau d'eau:</h4>
      <div class='legend'>
        <i class="fas fa-check safe"></i>
        <h4>Favorable</h4>
      </div>
      <div class='legend'>
        <i class="fas fa-times unsafe"></i>
        <h4>Défavorable</h4>
      </div>
      <h4>Alerte:</h4>
      <div class='legend'>
        <i class="fas fa-exclamation-triangle alert-level"></i>
        <h4>Praticable</h4>
      </div>
      <div class='legend'>
        <i class="fas fa-exclamation-triangle alert-level severity2"></i>
        <h4>Impraticable</h4>
      </div>
      <div class='search-ex'>
        <div>
          <h4>Exemple:</h4>
          <i class="fas fa-exclamation-triangle alert-level"></i>
          <i class="fas fa-check safe"></i>
        </div>
        <p>
          La rivière est praticable, mais attention un danger a été signalé sur ce parcours.
          Vous pouvez consulter le détail de l'alerte dans le topo.
        </p>
      </div>
        <i class="fas fa-times cross"></i>
    </div>
  </div>

<div class='container'>

  <%# SEARCH-BAR %>
  <div class='search'>
    <%= simple_form_for root_path, method: :get do |f| %>
      <div>
        <div class="search-form-control">
          <%= text_field_tag :query, params[:query], value: params[:query],class: "form-control string required", placeholder: "Trouver des topos" %>
          <button name="button" type="submit" class="btn btn-flat">
            <i class="fas fa-search"></i>
          </button>
        </div>
        <div id="filter">
          <div class="filter-grid">
            <% (1..6).each do |level| %>
                  <%= check_box_tag 'levels[]', level, params[:levels] && params[:levels].include?(level.to_s), {id: "level#{level}"} -%>
                  <label for="<%= "level#{level}" %>">
                    Niveau <%= int_to_roman(level) %>
                  </label>
            <% end %>
          </div>
          <button name="button" type="submit" class="btn-filter">
            <span>Filtrer</span>
          </button>
        </div>
      </div>
    <% end %>
  </div>


  <%# SEARCH-RESULT %>
    <% if @topos.count == 0 %>
      <h4 id='search-message'>Désolé nous ne trouvons aucun topo...</h4>
    <% elsif params[:query] == nil %>
      <h4 class='around'>
        <%= @topos.count <= 1 ? 'Topo à proximité' : 'Topos à proximité' %> (<%= @topos.count %>)
        <a class="info-btn"> i </a>
      </h4>
    <% else %>
      <h4 class='around'>
        <%= @topos.count <= 1 ? 'Topo' : 'Topos' %> (<%= @topos.count %>)
        <a class="info-btn"> i </a>
      </h4>
    <% end %>

  <%# LIST TOPOS %>
  <%= render 'shared/topos-cards', topos: @topos %>
</div>

app/views/topos/show.html.erb
<!-- app/views/topos/show.html.erb -->
<% content_for :meta_title,
              "#{@topo.river.name.capitalize} - #{@topo.name.capitalize} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @topo.name %>
<%# Désactivé : <% content_for :meta_image, cl_image_path(@offer.photo.path) %>

<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon" id="topo-header">
  <div>
    <%= "#{@topo.river.name.capitalize} - #{@topo.name.capitalize}"  %>
  </div>

  <div>
    <%= link_to toggle_favorite_topo_path(@topo), method: :post do %>
      <svg id="favorite-icon" class="<%= 'fav-active' if @favorite %>" width="35" height="32" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
      </svg>
    <% end %>
  </div>
</div>

<div class="container topo">
  <% if @topo.has_alert? %>
    <div class="alert-banner">
      <div id='alert-title'>
        <div>
          <i class="fas fa-exclamation-triangle"></i>
          <span><%= "#{"Alerte".pluralize(@alerts_count)} (#{@alerts_count})"%></span>
        </div>
        <i class="fas fa-chevron-down"></i>
      </div>
      <div class="alert-content">
        <% @comments.each do |comment| %>
          <% if comment.active %>
            <div class='alert-message'>
              <div class="alert-type">
                <h4>Type</h4>
                <span><%= comment.alert_type %></span>
              </div>
              <div class="alert-type">
                <h4>Praticable</h4>
                <span><%= comment.severity == 'Praticable' ? 'Oui' : 'Non' %></span>
              </div>
              <p><%= comment.description %></p>
              <h5>Posté le <%= comment.updated_at.strftime("%d") %>/<%= comment.updated_at.strftime("%m") %>/<%= comment.updated_at.year %> à <%= comment.updated_at.hour %>h<%= comment.updated_at.min %></h5>
              <div class='alert-status'>
                <h5>Danger toujours présent?</h5>
                <div>
                  <%= link_to 'oui', topo_path(@topo), class: 'btn-red' %>
                  <%= link_to 'non', topo_comment_path(@topo, comment), method: :patch ,class: 'btn-yellow' %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>

  <div id="key-info">
    <div class='key-text'>
      <h4>Difficulté</h4>
      <span><%= @topo.find_level.count > 1 ? "#{@topo.find_level[0]} - #{@topo.find_level[1]}" : "#{@topo.find_level[0]}" %></span>
      <h4>Longueur</h4>
      <span><%= "#{@topo.length}" %></span>
      <h4>Départ</h4>
      <span><%= @departure.name.capitalize %></span>
      <h4>Arrivée</h4>
      <span><%= @arrival.name.capitalize %></span>
    </div>
  </div>

  <%= link_to 'Signaler un danger', new_topo_comment_path(@topo), class: 'btn-alert'%>

  <div id="water-info">
        <%# <%= line_chart @data, %>
      <%= line_chart river_data_topo_path(@topo),
          id:"water-graph",
          width: "100%", height: "100%",
          ytitle: "Vol. d'eau (m3)", xtitle: "Date",
          style: "display:",
          legend: true,
          points: false,
          loading: "Chargement en cours... 🚣‍♀️ 🎣 ",
          empty: "Aucune donnée disponible 😱"
          %>
    <%# <div id="water-temp">
      <h3>2°</h3>
    </div> %>
  </div>

</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>